// <auto-generated />
namespace PhantomNet.AspNetCore.RemoteFolder
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.AspNetCore.RemoteFolder.Strings", typeof(Strings).GetTypeInfo().Assembly);

        /// <summary>
        /// The file {0} could not be found.
        /// </summary>
        internal static string FileNotFoundError
        {
            get { return GetString("FileNotFoundError"); }
        }

        /// <summary>
        /// The file {0} could not be found.
        /// </summary>
        internal static string FormatFileNotFoundError(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("FileNotFoundError"), p0);
        }

        /// <summary>
        /// Type {0} must derive from {1}&lt;{2}&gt;.
        /// </summary>
        internal static string InvalidServiceType
        {
            get { return GetString("InvalidServiceType"); }
        }

        /// <summary>
        /// Type {0} must derive from {1}&lt;{2}&gt;.
        /// </summary>
        internal static string FormatInvalidServiceType(object p0, object p1, object p2)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("InvalidServiceType"), p0, p1, p2);
        }

        /// <summary>
        /// There is no file to upload.
        /// </summary>
        internal static string NoFileToUploadError
        {
            get { return GetString("NoFileToUploadError"); }
        }

        /// <summary>
        /// There is no file to upload.
        /// </summary>
        internal static string FormatNoFileToUploadError()
        {
            return GetString("NoFileToUploadError");
        }

        /// <summary>
        /// There are more than one file to upload to a single position.
        /// </summary>
        internal static string ToManyFilesToUploadError
        {
            get { return GetString("ToManyFilesToUploadError"); }
        }

        /// <summary>
        /// There are more than one file to upload to a single position.
        /// </summary>
        internal static string FormatToManyFilesToUploadError()
        {
            return GetString("ToManyFilesToUploadError");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
